import streamlit as st
import string

st.set_page_config(page_title="🔠 Text to Emoji Converter", page_icon="😀")

st.title("🔠 Text to Emoji Converter")
st.write("Enter your text below. Words will be converted into emojis where possible.")

# Large, rich emoji dictionary
emoji_dict = {
    "hi": "👋",
    "hello": "👋",
    "how": "❓",
    "you": "👉",
    "i": "🙋",
    "am": "😊",
    "happy": "😊",
    "sad": "😢",
    "love": "❤️",
    "good": "👍",
    "great": "🌟",
    "fire": "🔥",
    "sun": "☀️",
    "star": "⭐",
    "party": "🎉",
    "money": "💰",
    "coffee": "☕",
    "music": "🎵",
    "dog": "🐶",
    "cat": "🐱",
    "pizza": "🍕",
    "cake": "🎂",
    "birthday": "🎈",
    "thanks": "🙏",
    "bye": "👋",
    "yes": "✅",
    "no": "❌",
    "question": "❓",
    "ok": "👌",
    "cool": "😎",
    "heart": "❤️",
    "home": "🏠",
    "car": "🚗",
    "phone": "📱",
    "computer": "💻",
    "book": "📚",
    "tree": "🌳",
    "flower": "🌸",
    "rain": "🌧️",
    "snow": "❄️",
    "wind": "💨" ,
    "cloud": "☁️",
    "moon": "🌙",
    "night": "🌜",
    "day": "🌞",
    "time": "⏰",
    "clock": "🕰️",
    "food": "🍔",
    "drink": "🍹",
    "travel": "✈️",
    "world": "🌍",
    "family": "👪",
    "friend": "👫",
    "team": "👥",
    "work": "💼",
    "school": "🏫",
    "study": "📖",
    "play": "🎮",
    "game": "🎲",
    "sports": "⚽",
    "exercise": "🏋️",
    "health": "💪",
    "fun": "😄",
    "smile": "😊",
    "laugh": "😂",
    "cry": "😢",
    "angry": "😠",
    "surprised": "😲",
    "confused": "😕",
    "bored": "😴" ,
    "tired": "😪",
    "excited": "🤩",
    "scared": "😱",
    "nervous": "😬",
    "relaxed": "😌",
    "proud": "😌",
    "embarrassed": "😳",
    "ashamed": "😔",
    "grateful": "🙏",
    "sorry": "😞",
    "welcome": "👋",
    "congratulations": "🎉",
    "goodbye": "👋",
    "yes": "👍",
    "no": "👎",
    "maybe": "🤷",
    "help": "🆘",
    "stop": "🛑",
    "start": "▶️",
    "pause": "⏸️",
    "play": "▶️",
    "record": "⏺️",
    "fast": "⏩",
    "slow": "⏪",
    "forward": "➡️",
    "backward": "⬅️",
    "left": "⬅️",
    "right": "➡️",
    "up": "⬆️",
    "down": "⬇️",
    "ok": "👌",
    "good": "👍",
    "bad": "👎",
    "nice": "😊",
    "awesome": "😎",
    "amazing": "🤩",
    "fantastic": "🌟",
    "wonderful": "🌈",
    "beautiful": "😍",
    "ugly": "😖",
    "funny": "😂",
    "serious": "😐",
    "boring": "😴",
    "interesting": "🤔",
    "exciting": "🤩",
    "difficult": "😓",
    "easy": "😌",
    "hard": "💪",
    "simple": "👌",
    "complex": "🧩",
    "complicated": "🧩",
    "important": "‼️",
    "urgent": "🚨",
    "necessary": "✅",
    "optional": "❓",
    "available": "🆗",
    "busy": "🚶",
    "free": "🆓",
    "new": "🆕",
    "old": "🕰️",
    "young": "👶",
    "old": "👴",
    "rich": "💰",
    "poor": "💸",
    "happy": "😊",
    "sad": "😢",
    "angry": "😠",
    "scared": "😱",
    "surprised": "😲",
    "confused": "😕",
    "bored": "😴",
    "tired": "😪",
    "excited": "🤩",
    "nervous": "😬",
    "relaxed": "😌",
    "proud": "😌",
    "embarrassed": "😳",
    "ashamed": "😔",
    "grateful": "🙏",
    "sorry": "😞",
    "welcome": "👋",
    "congratulations": "🎉",
    "goodbye": "👋",
    "yes": "👍",
    "no": "👎",
    "maybe": "🤷",
    "help": "🆘",
    "exam": "📚",
    "test": "📝",
    "question": "❓",
    "answer": "✅",
    "problem": "❗",
    "solution": "💡",
    "idea": "💡",
    "project": "📊",
    "meeting": "📅",
    "deadline": "⏰",
    "success": "🏆",
    "failure": "❌",
    "goal": "🎯",
    "achievement": "🏅",
    "challenge": "💪",
    "opportunity": "🌟",
    "risk": "⚠️",
    "reward": "🎁",
    "strategy": "🗺️",
    "plan": "📝",
    "team": "👥",
    "leader": "👑",
    "member": "👤",
    "collaboration": "🤝",
    "communication": "💬",
    "feedback": "📝",
    "support": "🤗",
    "motivation": "💪",
    "inspiration": "🌈",
    "innovation": "💡",
    "creativity": "🎨",
    "design": "🎨",
    "development": "💻",
    "testing": "🧪",
    "deployment": "🚀",
    "maintenance": "🔧",
    "bug": "🐛",
    "error": "❗",
    "issue": "⚠️",
    "where": "📍",
    "when": "⏰",
    "why": "❓",
    "how": "❓",
    "who": "👤",
    "what": "❓",
    "which": "❓",
    "weather": "☀️",
    "do": "✅",
    "don't": "❌",
    "like": "👍",
    "dislike": "👎",
    "want": "👉",
    "need": "🆘",
    "try": "🤔",
    "did": "✅",
    "make": "🛠️",
    "will": "✅",
    "can": "👍",
    "can't": "❌",
    "should": "✅",
    "shouldn't": "❌",
    "could": "👍",
    "couldn't": "❌",
    "would": "👍",
    "wouldn't": "❌",
    "must": "‼️",
    "mustn't": "❌",
    "might": "🤔",
    "mightn't": "❌",
    "shall": "✅",
    "shan't": "❌",
    "may": "✅",
    "mayn't": "❌",
    "shall": "✅",
    "shan't": "❌",
    "let's": "🤝",
    "let us": "🤝",
    "let's go": "🚀",
    "let's do it": "💪",
    "let's try": "🤔",
    "let's make": "🛠️",
    "let's have": "🍽️",
    "let's be": "🤗",
    "you're": "👉  ",
    "ypu": "👉",
    "your": "👉",
    "yours": "👉",
    "we": "👥",
    "us": "👥",
    "our": "👥",
    "ours": "👥",
    "they": "👥",
    "them": "👥",
    "their": "👥",
    "theirs": "👥",
    "he": "👤",
    "him": "👤",
    "his": "👤",
    "she": "👤",
    "her": "👤",
    "hers": "👤",
    "it": "📦",
    "am": "😊" ,
    "is": "✅",
    "are": "✅",
    "was": "✅",
    "were": "✅",
    "be": "✅",
    "been": "✅",
    "being": "✅",
    "have": "✅",
    "has": "✅",
    "had": "✅",
    "having": "✅",
    "do": "✅",
    "does": "✅",
    "well": "👍",
    "bad": "👎",
    "good": "👍",
    "better": "👍",
    "best": "🏆",
    "worse": "👎",
    
}

def convert_text_to_emoji(text):
    words = text.split()
    converted = []
    for word in words:
        # Remove punctuation and lowercase
        word_clean = word.lower().strip(string.punctuation)
        if word_clean in emoji_dict:
            converted.append(emoji_dict[word_clean])
        else:
            converted.append(word)
    return " ".join(converted)

# Input text
user_input = st.text_area("Enter your text here:", height=150)

if st.button("Convert"):
    if user_input.strip() == "":
        st.warning("Please enter some text to convert.")
    else:
        converted_text = convert_text_to_emoji(user_input)
        st.subheader("Converted Text:")
        st.write(converted_text)
        st.success("Text converted to emojis successfully!")
else:
    st.info("Click the button to convert your text to emojis.")
